name: pynamod

channels:
  - conda-forge
  - pip

dependencies:
  - python=3.13
  - pip
  - ipykernel
  - biopython
  - mdanalysis
  - pypdb
  - numba
  - nglview=3.1.4
  - setuptools<80
  - seaborn
  - more-itertools
  - pytest
  - ipywidgets
  - onnxruntime

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - torch
      - pdb2pqr
