name: pynamod

channels:
  - conda-forge
  - pip

dependencies:
  - python=3.13.12
  - pip
  - ipykernel
  - biopython=1.86
  - numpy=2.4.3
  - pandas=3.0.1
  - mdanalysis=2.10.0
  - pypdb=2.4
  - numba=0.64.0
  - nglview=3.1.4
  - setuptools<80
  - seaborn=0.13.2
  - more-itertools=10.8.0
  - pytest=9.0.2
  - ipywidgets=8.1.7
  - networkx<3.6.1
  - onnxruntime=1.24.2

  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu130
      - --find-links https://data.pyg.org/whl/torch-2.9.0+cu130.html
      - torch==2.9.*
      - pdb2pqr
