channels:
  - pytorch
  - defaults
  - conda-forge
  - nvidia
  - pip

dependencies:
  - python=3.11.9
  - ipykernel
  - pypdb=2.4
  - numba
  - nglview=3.0.3
  - pytorch=2.3.1
  - pytorch-cuda=12.1
  - seaborn
  - more-itertools
  - pytest
  - ipywidgets
  - h5py
  - biopython
  - scikit-learn=1.4.2
  - pip:
      - pdb2pqr
      - mdanalysis
